### PR TITLE
chore: run flarum-cli audit infra --fix

### PR DESCRIPTION
**Pull request by datlechin**

### CODE REVIEW

**Comment by ramesh-dada** [comment]
@datlechin Thanks for the pull request :-)

**Comment by ramesh-dada** [comment]
@datlechin The build is failing seems like there's a path issue somewhere

**Comment by ramesh-dada** [comment]
Oh wait we don't really need to build this extension, I am making a release.

**Comment by datlechin** [comment]
That's because the repo doesn't have `js` for build.
You can remove the github workflow

**Pull request merged**
